services:

  agent:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LLM_SERVICE_URL=http://host.docker.internal:8001
    build:
      context: ./services/agent
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/workspace
      - ./config:/config
    depends_on:
      - stt
      - llm
      - tts


  stt:
    build:
      context: ./services/stt
    volumes:
      - model-cache:/models

  llm:
    ports:
      - "8001:8000"
    build:
      context: ./services/llm
    volumes:
      - model-cache:/models

  tts:
    build:
      context: ./services/tts
    volumes:
      - model-cache:/models

  ui:
    build:
      context: ./services/ui
    depends_on:
      - agent

volumes:
  model-cache: